version: '3.8'
services: 
  account_service:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'pytest src/presenters/controllers/updated_user/ -v -s'
    # command: 'python3 server.py' ecommerce-account-service-jvbs
    command: 'gunicorn -w 5 -b 0.0.0.0:5000 "server:create_app()"'
    # command: 'alembic upgrade head' # executar migration
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    depends_on: 
      - db


  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33068:3306