version: '3.8'
services: 
  account_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'pytest src/presenters/controllers/activate_user/ -v -s'
    # command: 'alembic upgrade head' # executar migration
    ports:
      - 8001:5000
    volumes: 
      - .:/app
    depends_on: 
      - db


  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33068:3306